/*
 * Campus Incident API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Geolocation;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Location
 */


public class Location {
  @SerializedName("center")
  private Geolocation center = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("radius")
  private Double radius = null;

  @SerializedName("tzName")
  private String tzName = null;

  public Location center(Geolocation center) {
    this.center = center;
    return this;
  }

   /**
   * Get center
   * @return center
  **/
  @Schema(description = "")
  public Geolocation getCenter() {
    return center;
  }

  public void setCenter(Geolocation center) {
    this.center = center;
  }

  public Location id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Location name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Location radius(Double radius) {
    this.radius = radius;
    return this;
  }

   /**
   * In meters
   * minimum: 0
   * @return radius
  **/
  @Schema(description = "In meters")
  public Double getRadius() {
    return radius;
  }

  public void setRadius(Double radius) {
    this.radius = radius;
  }

  public Location tzName(String tzName) {
    this.tzName = tzName;
    return this;
  }

   /**
   * Get tzName
   * @return tzName
  **/
  @Schema(required = true, description = "")
  public String getTzName() {
    return tzName;
  }

  public void setTzName(String tzName) {
    this.tzName = tzName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Location location = (Location) o;
    return Objects.equals(this.center, location.center) &&
        Objects.equals(this.id, location.id) &&
        Objects.equals(this.name, location.name) &&
        Objects.equals(this.radius, location.radius) &&
        Objects.equals(this.tzName, location.tzName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(center, id, name, radius, tzName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Location {\n");
    
    sb.append("    center: ").append(toIndentedString(center)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    radius: ").append(toIndentedString(radius)).append("\n");
    sb.append("    tzName: ").append(toIndentedString(tzName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
